# Generated by Django 4.2.7 on 2025-11-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pan_card', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('money', 'Money'), ('things', 'Things')], max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('things', models.TextField(blank=True, null=True)),
                ('donor_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('affiliated', 'Affiliated'), ('corporate', 'Corporate'), ('grant', 'Grant/Foundation')], max_length=20)),
                ('family_member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('family_member_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('family_member_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('affiliated_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliated_position', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliated_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('corporate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('corporate_address', models.TextField(blank=True, null=True)),
                ('corporate_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('corporate_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('foundation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('foundation_address', models.TextField(blank=True, null=True)),
                ('foundation_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('foundation_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(max_length=500)),
                ('message', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking')], max_length=20, null=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donations',
                'indexes': [models.Index(fields=['email'], name='donations_email_ffdd61_idx'), models.Index(fields=['receipt_number'], name='donations_receipt_e4bd90_idx'), models.Index(fields=['created_at'], name='donations_created_f10839_idx')],
            },
        ),
    ]
